### ISSUE TITLE
Replace rheostats with PWM ?

### ISSUE THREAD

**Issue by carpii** [eyewriter/eyewriter#15]
Sorry to use github as a forum, but in 4 months this is the only place I've ever had a reply from anyone remotely knowledgable about eyewriter. I really appreciate it by the way :)

For my eyewriter, it seems one of the first obstacles to calibration, is having to repeatedly twiddle the rheostats. It varies depending on distance from cam, and seems to be easily knocked out of kilter.

I had a thought that maybe they could be replaced by controlling the led brightness from the arduino, via PWM. I wonder what anyone elses thoughts about this are, whether its impractical or whether theres issues I havent considered ?

On the face of it, it sounds doable.

Another idea might be to replace the rheostats with digital potentiometers, but Im not convinced I've found any that would be suitable yet.

Thanks

**Comment by ofZach** [comment]
greetings -- yes we haven't always been active on the eyewriter forum because we've been busy and it's easy to loose track of new posts there.  We've also had some spam problems there. 

I'm curious about your setup for the most part .  Can you possibly photograph how you've installed the EW (both the physical install and screenshots of the software) ?

I suspect PWM could work for doing an auto-adjustment -- but I'm curious to see what the issues you are having are too...

**Comment by carpii** [comment]
Hi Zach, thanks for the reply :)

Im actually in the middle of reworking my breadboard eyewriter into a soldered stripboard, so I cant provide any photos of it in action right now. Hopefully I can in the next few days though. 
Generally, the issue Im having is that the rheostats seem to work fine so long as the head remains in a fixed position, but any sort of z-axis head adjustment results in them having to be tweaked (in addition to refocusing the camera, naturally). Its probably best demonstrated by a video though, as you say 

Regarding the eyewriter forum, I would be happy to help moderate this if you want. I imagine you have quite a few plates spinning with your projects.

I made a forum post to a similar effect, but its been drowned out by the spam, and I'd love to see the official forums foster a bigger dev community.

Thanks

**Comment by kylemcdonald** [comment]
i started developing some auto-adjusting solutions with golan last summer, but we quickly would that pwm won't work due to the cmos sensor on the ps3eye. with a global shutter like the firefly you're ok, but for the ps3eye you absolutely need digital pots.

though, if you use a pwm at a very high frequency you can get something like 2 lines on, 2 lines off... (2 instead of 1 due to bayer interpolation) which lends itself to the possibility of single-frame eye tracking at 60 fps... :) (albeit halved vertical resolution) http://www.flickr.com/photos/kylemcdonald/3781440085/ haven't tried this yet in practice...

**Comment by carpii** [comment]
Thanks Kyle,

Thats very interesting, and will probably save me a lot of time instead of trying to get PWM working, given that Im using a ps3 eye.

I've since been looking for digital pots, but Im not overly familiar with them, and so far they seem to be on a much larger resistance then I need (and thus much larger steps).
I'll maybe abandon this idea and try to work on improving autocalibration via the software only.   

60 fps looks very cool, but a bridge too far for me right now. Something which might be worth investigating later though :-)
